### PR TITLE
update blog image references relative to /blog

### PR DESCRIPTION
**Pull request by detaybey**

### CODE REVIEW

**Review by yufufi — APPROVED** [review]

**Comment by enesunal** [comment]
See comment on code

**Comment by enesunal** [comment]
Why did we merged this straight away although we have an unanswered comment on the review?

**Comment by detaybey** [comment]
sorry didn't see the comment, well your solution makes perfect sense. let me try and make it work like that.

**Comment by enesunal** [comment]
Hmm, as @yufufi told me; it wouldn't work since the full path would be 

http://www.deepnetwork.com/blog///2019/11/08/images/blabla.png

for this blog post:

http://www.deepnetwork.com/blog///2019/11/08/oauth2-oicd-pkce.html


So, nevermind :)

**Comment by detaybey** [comment]
Sadly, this time the permalink would be a problem. 
Try this, and remove the /post/ prefix to see for yourself.

https://deepnetworkgmbh.github.io/blog///2019/11/08/oauth2-oicd-pkce.html

Savas told me to get this done by the end of today, so as it may look hacky it works both with deepnetwork.com/blog and permalinks. If you have a better solution please let me know.

Screen Shot 2019-11-28 at 18 43 20

**Comment by detaybey** [comment]
Ah, there you go... Ok we're on the same page.

**Pull request merged**
